# Generated by Django 5.2.8 on 2025-11-26 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("domains", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="domain",
            options={"verbose_name": "Domain", "verbose_name_plural": "Domains"},
        ),
    ]
