# Generated by Django 5.2.8 on 2025-11-26 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('latency_ms', models.FloatField(help_text='Tiempo de respuesta en milisegundos')),
                ('status_code', models.IntegerField(help_text='Código de estado HTTP (ej: 200, 404, 500)')),
                ('is_success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pings', to='domains.domain')),
            ],
            options={
                'ordering': ['-checked_at'],
                'indexes': [models.Index(fields=['domain', '-checked_at'], name='monitoring__domain__fbb6e6_idx')],
            },
        ),
    ]
