# Generated by Django 5.2.8 on 2025-11-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pingresult",
            name="latency_ms",
            field=models.FloatField(help_text="Response time in milliseconds"),
        ),
        migrations.AlterField(
            model_name="pingresult",
            name="status_code",
            field=models.IntegerField(
                help_text="HTTP status code (e.g.: 200, 404, 500)"
            ),
        ),
    ]
